name = "backend"
compatibility_date = "2024-08-23"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiN2UyNWMzYjYtZDA5OC00YzhhLWI5MmUtZGVkZWJkZWQ2ZTg2IiwidGVuYW50X2lkIjoiNjhmZWE5NWM5NjZiM2NmZTZjNjc3OGI0Y2NlNGY5Mjc5YjA4NjE5YWE4ZTFkOTRjMGIyOGFkZDIyNDYxYzdiNSIsImludGVybmFsX3NlY3JldCI6ImE2OGQ3ZDBkLTJiZWItNDRiZi1hYTAzLTNiYWMxNzkwOTA0YyJ9.47pstjm83P9FQ4DuUiFq1HwjqrRDVACj6FJxeO9Ipco"
JWT_SECRET="1234"